### ISSUE TITLE
TPTweakShakeWindow can only use on DEBUG mode

### ISSUE THREAD

**Issue by haerul-rijal** [tokopedia/ios-tptweak#8]
Is there any way we can customize the environment? 
For example we have:
- `DEBUG`
- `STAGING`
- `PRODUCTION`
and we want to enable this on `DEBUG` & `STAGING`

https://github.com/tokopedia/ios-tptweak/blob/68f35b258fbca6cd90c5a53769d9fa42329e02d5/Sources/TPTweak/TPTweakShakeWindow.swift#L31-L40

**Comment by wendyliga** [comment]
hi @haerul-rijal, implementing this directly on `TPTweakShakeWindow` will reduce the flexibility, as all implementor will also need to adapt this rules.

so instead of this, you can add this logic, when initializing the UIWindow

```
#if DEBUG
window = TPTweakShakeWindow(frame:...)
# else 
window = UIWindow(frame: ...)
```

**Comment by haerul-rijal** [comment]
@wendyliga Thank you.
